### ISSUE TITLE
Create and Update methods in CRUDRepository should return the updated entity, not Void

### ISSUE THREAD

**Issue by volbap** [inaka/Jayme#37]
In order to keep consistence with the latest values that an entity can take and give the `ViewController` layer more flexibility to work with entities, `create` and `update` methods in `CRUDRepository` should not return `Future <Void, JaymeError>` but rather `Future <EntityType, JaymeError>`, containing the updated entity.

This issue came up as soon as we started discussing #22 .

**Comment by pablolvillar** [comment]
**Renaming process checklist:**

- [ ] Every appearance in code is renamed
- [ ] Every according file is renamed
- [ ] Project builds successfully
- [ ] Tests pass successfully
- [ ] There's a deprecation/migration mechanism implemented in code
- [ ] README is updated
- [ ] CHANGELOG is updated
