### ISSUE TITLE
Change Create path

### ISSUE THREAD

**Issue by agerace** [inaka/Jayme#63]
Change create method path to execute a request to `:endpoint/`  instead of `:endpoint/:id`.

**Comment by volbap** [comment]
This issue has already been discussed in #22 . Closing this one. If required, we will re-open #22. I'm open to discussions.

**Comment by volbap** [comment]
Finally, I've decided to solve it in this issue.

As @elbrujohalcon states, we can have a POST request containing an id, but that id would appear within the body of the request, not in the URL.
We need to change that.
